sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf {{ cookiecutter.series.upper() }}-{{ cookiecutter.serial_number }}.pdf --upload --lsstdoc {{ cookiecutter.series.upper() }}-{{ cookiecutter.serial_number }}.tex --env=travis --ltd-product {{ cookiecutter.series.lower() }}-{{ cookiecutter.serial_number }}"
env:
  global:
    # Add LSST the Docs credentials
